version: "3.7"
services:
  prometheus:
    image: "prom/prometheus"
    restart: on-failure
    ports:
      - 9090:9090
    volumes:
      - ./third-party/prometheus:/etc/prometheus

  grafana:
    image: "grafana/grafana"
    depends_on:
      - prometheus
      - jaeger
    restart: on-failure
    ports:
      - "9413:3000"

  # DISABLE jaeger IF USING zipkin
  # zipkin:
    # image: "openzipkin/zipkin"
    # restart: on-failure
    # ports:
      # - "9412:9411"

  jaeger:
    image: jaegertracing/all-in-one:latest
    container_name: jaeger
    restart: on-failure
    ports:
      - 5775:5775/udp
      - 6831:6831/udp
      - 6832:6832/udp
      - 5778:5778
      - 16686:16686
      - 14268:14268
      - 14250:14250
      - 9411:9411
    # environment:
    # - SPAN_STORAGE_TYPE=elasticsearch
    # - ES_SERVER_URLS=http://elasticsearch:9200
    # depends_on:
    #- 'elasticsearch'

  # DISABLE filebeat IF USING logstash
  # logstash:
    # image: docker.elastic.co/logstash/logstash:7.9.3
    # container_name: logstash
    # ports: ['9600:9600']
    # depends_on: ['elasticsearch']
    # volumes:
      # - './etc/logstash/pipeline:/usr/share/logstash/pipeline'
      # - './var/log:/log'

  filebeat:
    image: docker.elastic.co/beats/filebeat:7.9.3
    container_name: filebeat
    restart: on-failure
    user: root
    volumes:
      - './var/filebeat/log/:/var/log/:ro'
      - './var/filebeat/docker.sock:/var/run/docker.sock'
      - './var/log/:/var/lib/docker/containers/log:ro'
      - './etc/filebeat/filebeat.yml:/usr/share/filebeat/filebeat.yml'
    command: [ "setup", "--strict.perms=false" ]
    depends_on:
      - 'elasticsearch'

  kibana:
    image: docker.elastic.co/kibana/kibana:7.9.3
    container_name: kibana
    restart: on-failure
    ports: [ '5601:5601' ]
    depends_on:
      - 'elasticsearch'
    
