version: '3.8'
services:
    elastic:
        image: docker.elastic.co/elasticsearch/elasticsearch:7.13.0
        container_name: elastic
        ulimits:
            memlock:
              soft: -1
              hard: -1
        environment:
            - node.name=elastic
            - discovery.type=single-node
            - cluster.name=es-docker-cluster
            - bootstrap.memory_lock=true
            - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
        ports:
            - 9200:9200
